# filepath: wrangler.toml
name = "strawbears" # Replace with your worker's name
main = "bot.py"        # Replace with your entry file if different
compatibility_date = "2025-04-10"

[compatibility_flags]
python_workers = true